/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      fontFamily: {
        heading: ['"Playfair Display"', '"Noto Serif KR"', '"Pretendard"', 'serif'],
        body: ['"Pretendard"', '"Noto Sans KR"', '-apple-system', 'sans-serif'],
        serif: ['"Playfair Display"', '"Noto Serif KR"', 'Georgia', 'serif'],
        label: ['"Pretendard"', '"Noto Sans KR"', 'sans-serif'],
        sans: ['"Pretendard"', '"Noto Sans KR"', 'sans-serif'],
      },
      transitionDuration: {
        '700': '700ms',
      },
      transitionTimingFunction: {
        'out-ace': 'cubic-bezier(0.25, 1, 0.5, 1)',
      },
      letterSpacing: {
        'tightest': '-0.03em',
      },
      colors: {
        ace: {
          base: '#f4f3ee',
          hover: '#e8e6df',
          main: '#1a1a1a',
          brick: '#8C2318',
          olive: '#4A5340',
          muted: '#666666',
        },
        background: {
          50: 'oklch(var(--background-50))',
          100: 'oklch(var(--background-100))',
          200: 'oklch(var(--background-200))',
          300: 'oklch(var(--background-300))',
          400: 'oklch(var(--background-400))',
          500: 'oklch(var(--background-500))',
          600: 'oklch(var(--background-600))',
          700: 'oklch(var(--background-700))',
          800: 'oklch(var(--background-800))',
          900: 'oklch(var(--background-900))',
          950: 'oklch(var(--background-950))',
        },
        primary: {
          50: 'oklch(var(--primary-50))',
          100: 'oklch(var(--primary-100))',
          200: 'oklch(var(--primary-200))',
          300: 'oklch(var(--primary-300))',
          400: 'oklch(var(--primary-400))',
          500: 'oklch(var(--primary-500))',
          600: 'oklch(var(--primary-600))',
          700: 'oklch(var(--primary-700))',
          800: 'oklch(var(--primary-800))',
          900: 'oklch(var(--primary-900))',
          950: 'oklch(var(--primary-950))',
        },
        accent: {
          50: 'oklch(var(--accent-50))',
          100: 'oklch(var(--accent-100))',
          200: 'oklch(var(--accent-200))',
          300: 'oklch(var(--accent-300))',
          400: 'oklch(var(--accent-400))',
          500: 'oklch(var(--accent-500))',
          600: 'oklch(var(--accent-600))',
          700: 'oklch(var(--accent-700))',
          800: 'oklch(var(--accent-800))',
          900: 'oklch(var(--accent-900))',
          950: 'oklch(var(--accent-950))',
        },
        secondary: {
          50: 'oklch(var(--secondary-50))',
          100: 'oklch(var(--secondary-100))',
          200: 'oklch(var(--secondary-200))',
          300: 'oklch(var(--secondary-300))',
          400: 'oklch(var(--secondary-400))',
          500: 'oklch(var(--secondary-500))',
          600: 'oklch(var(--secondary-600))',
          700: 'oklch(var(--secondary-700))',
          800: 'oklch(var(--secondary-800))',
          900: 'oklch(var(--secondary-900))',
          950: 'oklch(var(--secondary-950))',
        },
        foreground: {
          50: 'oklch(var(--foreground-50))',
          100: 'oklch(var(--foreground-100))',
          200: 'oklch(var(--foreground-200))',
          300: 'oklch(var(--foreground-300))',
          400: 'oklch(var(--foreground-400))',
          500: 'oklch(var(--foreground-500))',
          600: 'oklch(var(--foreground-600))',
          700: 'oklch(var(--foreground-700))',
          800: 'oklch(var(--foreground-800))',
          900: 'oklch(var(--foreground-900))',
          950: 'oklch(var(--foreground-950))',
        },
      },
    },
  },
  plugins: [],
}